web_flask/main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

# inicialização
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

# execução
app.run(debug=True)

web_flask/routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

"""
Rota de Clientes

    - /clientes/ (GET) - Listar os clientes
    - /clientes/ (POST) - inserir o cliente no servidor
    - /clientes/new (GET) - renderizar o formulario para criar um cliente
    - /clientes/<id> (GET) - obter os dados de um cliente
    - /clientes/<id>/edit (GET) - renderizar um formulario para editar um cliente
    - /clientes/<id>/update (PUT) - atualizar os dados do cliente
    - /cliente/<id>/delete (DELETE) - deleta o registro do cliente
"""


@cliente_route.route('/')
def lista_clientes():
    """ listar os clientes """
    return render_template('lista_clientes.html', clientes=CLIENTES)


@cliente_route.route('/', methods=['POST'])
def inserir_clientes():
    """ inserir dados do cliente """
    
    data = request.json
    
    novo_usuario = {
        'id': len(CLIENTES) + 1,
        'nome': data['nome'],
        'email': data['email'], 
    }
    
    CLIENTES.append(novo_usuario)
    
    
    return render_template('item_cliente.html', cliente=novo_usuario)


@cliente_route.route('/new')
def form_cliente():
    """ formulario para cadastrar um cliente """
    return render_template('form_cliente.html')


@cliente_route.route('/<int:client_id>')
def detalhe_cliente(cliente_id):
    """ exibir detalhes do cliente """
    return render_template('detalhe_cliente.html')


@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    """ formulario para editar um cliente """
    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c
    
    return render_template('form_cliente.html', cliente=cliente)


@cliente_route.route('/<int:client_id>/update', methods=['PUT'])
def update_cliente(cliente_id):
    """ atualizar os dados do cliente """
    pass


@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):   
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id ]
    return {'deleted': 'ok'}

web_flask/routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)


@home_route.route('/')
def home():
    return render_template('index.html')

web_flask/templates/form_cliente.html
<form class="c-form" 
    {% if cliente %}
        action="{{ url_for('cliente.update_cliente', cliente_id=cliente.id) }}" 
    {% else %}
        action="{{ url_for('cliente.inserir_clientes') }}" 
    {% endif %}

    
    method="{% if cliente %}PUT{% else %}POST{% endif %}"

    c-append=".lista-clientes">

    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="text" class="form-control" name="nome" {% if cliente%}value="{{cliente.nome}}"{% endif %}>
    </div>

    <div class="mb-3">
        <label id="label-target" class="form-label">Email</label>
        <input type="text" class="form-control" name="email" {% if cliente%}value="{{cliente.email}}"{% endif %}>
    </div>

    <button type="submit" class="btn btn-primary">
        {% if cliente%} Salvar{% else %}Criar{% endif %}
    </button>

</form>

web_flask/templates/index.html
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
</head>

<body>

  <div class="container">

      <h1 class="text-center">Gestão de Clientes</h1>


    <!--Formulario clientes-->
    <div id="form-cliente" 
    c-container="{{ url_for('cliente.form_cliente') }}"></div>
    
    
    
    <hr>


    <!--Lista clientes-->
    <h2>Lista de clientes</h2>
    <div c-container="{{ url_for('cliente.lista_clientes')}}"></div>
  </div>
  






  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>

</html>

web_flask/templates/item_cliente.html
<tr>
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome}}</td>
    <td>{{ cliente.email}}</td>
    <td>

      <button class="btn btn-primary" 
            c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}"
            c-target="#form-cliente">
                Editar
        </button>
      
      <button 
        class="btn btn-danger" 
        c-delete=" {{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}"
        c-remove-closest="tr">Deletar
      </button>
    </td>
  </tr>

web_flask/templates/lista_clientes.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>

  <tbody id="lista-clientes">

    {% for cliente in clientes %}
        {% include 'item_cliente.html' %}
    {% endfor %}

  </tbody>
</table>